server:
  port: 8080
  host: "0.0.0.0"

mysql:
  host: "192.168.131.130"
  port: 3306
  user: "root"
  password: "123456"
  database: "ssl_monitor"

# redis:
#   host: "localhost"
#   port: 6379
#   db: 0

email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  username: ""
  password: ""
  from_address: "" 